services:

    monerod:
        container_name: monerod
        build: .
        environment:
            - BATCH_SIZE=1
            - PROXY_URL=socks5://${TORSOCKS_TOR_ADDRESS}:9050
            - PRUNE_BLOCKCHAIN=true
        volumes:
            - "./data-local:/media/monerod"
        ports:
            - "127.0.0.1:18081:18081"
            - "127.0.0.1:18082:18082"
            - "127.0.0.1:18083:18083"
